<?php

/**
 * @file
 *
 * Defines any Backdrop CMS hooks needed for the module.
 *
 * Yes, there is almost no code in the .module file. Migrate operates almost
 * entirely through classes, and by adding any files containing class
 * definitions to migrate_example_autoload_info() below, those files are
 * automatically included only when the classes they contain are referenced.
 *
 * The one non-class piece you need to implement is hook_migrate_api(), but
 * because .migrate.inc is registered using hook_hook_info, by defining your
 * implementation of that hook in example.migrate.inc, it is automatically
 * invoked only when needed.
 */

/**
 * Implements hook_autoload_info().
 */
function migrate_example_autoload_info() {
  return array(
    'BeerTermMigration' => 'beer.inc',
    'BeerUserMigration' => 'beer.inc',
    'BeerNodeMigration' => 'beer.inc',
    'BeerCommentMigration' => 'beer.inc',
    'WinePrepMigration' => 'wine.inc',
    'WineVarietyMigration' => 'wine.inc',
    'WineRegionMigration' => 'wine.inc',
    'WineBestWithMigration' => 'wine.inc',
    'WineFileCopyMigration' => 'wine.inc',
    'WineFileBlobMigration' => 'wine.inc',
    'WineRoleMigration' => 'wine.inc',
    'WineUserMigration' => 'wine.inc',
    'WineProducerMigration' => 'wine.inc',
    'WineProducerXMLMigration' => 'wine.inc',
    'WineProducerNamespaceXMLMigration' => 'wine.inc',
    'WineProducerMultiXMLMigration' => 'wine.inc',
    'WineProducerMultiNamespaceXMLMigration' => 'wine.inc',
    'WineProducerXMLPullMigration' => 'wine.inc',
    'WineProducerNamespaceXMLPullMigration' => 'wine.inc',
    'WineWineMigration' => 'wine.inc',
    'WineCommentMigration' => 'wine.inc',
    'WineTableMigration' => 'wine.inc',
    'WineFinishMigration' => 'wine.inc',
    'WineUpdatesMigration' => 'wine.inc',
    'WineCommentUpdatesMigration' => 'wine.inc',
    'WineVarietyUpdatesMigration' => 'wine.inc',
    'WineUserUpdatesMigration' => 'wine.inc',
  );
}
