<?php

/**
 * @file
 * THIS FILE INTENTIONALLY LEFT BLANK.
 *
 * Yes, there is no code in the .module file. Migrate operates almost entirely
 * through classes, and by adding any files containing class definitions to the
 * .info file, those files are automatically included only when the classes they
 * contain are referenced. The one non-class piece you need to implement is
 * hook_migrate_api(), but because .migrate.inc is registered using
 * hook_hook_info, by defining your implementation of that hook in
 * example.migrate.inc, it is automatically invoked only when needed.
 */

/**
 * Implements hook_config_info().
 */
function migrate_example_config_info() {
  $prefixes['migrate.settings'] = array(
    'label' => t('migrate settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_autoload_info.
 */
function migrate_example_autoload_info() {
  return array(
    'BasicExampleMigration' => 'beer.inc',
    'AdvancedExampleMigration' => 'wine.inc',
  );
}
